### ISSUE TITLE
Parser does not work for every CIS type

### ISSUE THREAD

**Issue by thibon** [aws-samples/cis-benchmark-pdf-parser#1]
Hi Msntx,

First, thanks for you parser, it is the only one really working and understandable.

Parser works for your sample file but does not work for Windows CIS for example (Windows 2019 for instance) as the following line does not match :
```python
if findPage.searchFor("Recommendations 1 Initial Setup"):
```
Removing the "Initial Setup" makes it work :
```python
if findPage.searchFor("Recommendations 1 "):
```

Another specificity of the Windows CIS Benchmark are the rules containing "Audit" like "2.3.2.1 (L1) Ensure 'Audit: Force audit policy subcategory settings", making the var acnt incrementing thus messing the whole parsing.
Modifying the split like this makes it work:
```python
a_post = data.split("\nAudit:", 1)[1]
```

Still doesn't work for Windows 2016 but I don't have the time to look at it and don't need it for now. I didn't forked the project but I can and make a pull request if you want to.

**Comment by msntx** [comment]
Hey @thibon thank you for taking the time to test this out and look into the code. I did not make any efforts for the Windows Benchmarks, but it's clearly worth pursuing. I'll look into your suggestions. Thanks for the assistance.

**Comment by jeffdfield** [comment]
I think I'm having the same issue. I'm super new to Python so forgive me if I'm wrong. This is the output I'm getting.

c:\Temp\CIS2CSV>py cis_pdf_parser.py --pdf_file CIS_Microsoft_Windows_10_Enterprise_Release_21H1_Benchmark_v1.11.0.pdf --out_file output.csv
Deprecation: 'loadPage' removed from class 'Document' after v1.19.0 - use 'load_page'.
Deprecation: 'searchFor' removed from class 'Page' after v1.19.0 - use 'search_for'.
2021-12-10 09:47:13,765 INFO     *** Not a CIS PDF Benchmark, exiting. ***

**Comment by thibon** [comment]
@jeffdfield yes the Linux and Windows CIS are not formatted the exact same way so you will have to adjust the code, beginning with my modifications above

**Comment by jeffdfield** [comment]
![image](https://user-images.githubusercontent.com/38103397/145604814-87f4a35e-7ef0-436b-804a-575f0a47f000.png)
That's what I get now.

**Comment by thibon** [comment]
@jeffdfield you're on the way. You might want to take a look at my fork I've just pushed as it's working on Windows server, Windows 10 should not be too hard to update but I don't need it nor have the time right now.
Don't be surprised, I set the log level to DEBUG on my fork

**Comment by jeffdfield** [comment]
Still getting the same thing. Thanks for the help.

**Comment by msntx** [comment]
@thibon I've taken a look at your fork, if you're interested in having that added in, please submit a pull request on a feature branch.

**Comment by thibon** [comment]
@msntx definitely but I have to patch it as I broke your code somewhere, it does not work anymore on Linux CIS
